In [1]:
import numpy as np

In [2]:
# iterate 2- array using for loop 

arr=np.array([[1,2 ,3],[4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
#if iterate N-D array it will go through n-th dimension one by one 
#iterate each scalar element of 2-d array 

arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [4]:
# copy and views:-copy is a new array and the view is just a view of the original array 
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
arr[0]=10
print(arr)
print(x)

[10  2  3  4  5  6]
[1 2 3 4 5 6]


In [5]:
# view:-make a view throgh the original array and display both array 

arr=np.array([1,2,3,4,5,6])
x=arr.view()
arr[3]=12
print(arr)
print(x)

[ 1  2  3 12  5  6]
[ 1  2  3 12  5  6]


In [6]:
# 3-d array:-an array that has 2-D array(matrix) as its element is called 3-d array.
#these are often use to represnt 3rd order tenser

arr=np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
# Higher dimensional array:-an array can have any number of dimension when the array is created you can define the number of dimension by using "ndim" argument
arr=np.array([1,2,3,4], ndmin=5)
print(arr)
print("nymber of dimension :",arr.ndim)


[[[[[1 2 3 4]]]]]
nymber of dimension : 5


In [13]:
# creat an array with datatype 'string'
arr=np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [17]:
# creat an array with data type 4 bytes integer 

arr=np.array([1,2,3,4],dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [23]:
#  converting data types an existing array
# change data type float into integer by using "i" as a parameter value 

arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [25]:
# convert following element 1-D array with 12 element into 2-D array

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,4) # 3 rows with 4 element
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
# the outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
# iterate on the elements of the following 3-D array:

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print("x represents the 2-D array:")
    print(x)


x represents the 2-D array:
[[1 2 3]
 [4 5 6]]
x represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


In [32]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [34]:
# Iterating on Each Scalar Element:-In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [35]:
# terating Array With Different Data Types
# iterating through array as a string

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [38]:
# Iterating With Different Step Size, We can use filtering and followed by iteration.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [39]:
# Enumerated Iteration Using ndenumerate()
# Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.
 # Enumerate on following 1D arrays elements:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [40]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [41]:
# iterating with different step size 
# Iterate through every scalar element of the 2D array skipping 1 element:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:2,::2]):
    print(x)

1
3
5
7


In [43]:
# Joining NumPy Arrays:-oining means putting contents of two or more arrays in a single array.

arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr=np.concatenate((arr1, arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# join two array along row (axis-1)

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,3,4],[5,6,8]])
arr=np.concatenate((arr1,arr2), axis=1)
print(arr)

[[1 2 3 2 3 4]
 [4 5 6 5 6 8]]


In [46]:
# Joining Arrays Using Stack Function:-stack is same as concatenation there is only difference is that stacking is done along a new axis 
# We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other,that is stack
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,3,4],[5,6,8]])
arr=np.stack((arr1, arr2), axis=1)
print(arr)

[[[1 2 3]
  [2 3 4]]

 [[4 5 6]
  [5 6 8]]]


In [47]:
arr1=np.array([1,2,3])
arr2=np.array([2,3,4])
arr=np.stack((arr1,arr2), axis=1)
print(arr)

[[1 2]
 [2 3]
 [3 4]]


In [49]:
# staking along row for that we will use "hstack" to stack along row 

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,3,4],[5,6,8]])
arr=np.hstack((arr1,arr2))
print(arr)

[[1 2 3 2 3 4]
 [4 5 6 5 6 8]]


In [50]:
# stacking along coloumn for that we will use "vstack" to stack along coloumn

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,3,4],[5,6,8]])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 8]]


In [51]:
# stacking along hight and depth using 'dstack'
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,3,4],[5,6,8]])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [6 8]]]


In [53]:
# array split:-We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
# split the array in 3 part
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3) # split array in three part
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
# split 2-d array into three 2-D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr=np.array_split(arr,3 )
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [6]:
# searching array using "np.where"
arr = np.array([1, 2, 3, 4, 5, 4, 4])
newarr=np.where(arr==4)
print(newarr)

(array([3, 5, 6], dtype=int64),)


In [7]:
newarr=np.where(arr%2==0) # searching  even value through 'where' method
print(newarr)

(array([1, 3, 5, 6], dtype=int64),)


In [8]:
newarr=np.where(arr%2==1) # searching odd value 
print(newarr)

(array([0, 2, 4], dtype=int64),)
